== Mapping change

=== General


A mapping change records modifications to the mapping of an EXPRESS schema to
another schema or representation.

The structure is built on the following constructs:

* Edition changes: Details changes made to this edition of the mapping specification
against the previous version.

* Item changes: Specific elements in the mappings that were changed in this edition.

Syntax:

[source,yaml]
----
schema: String (required)
  # Name of the EXPRESS schema
editions:
  - {edition change 1}
  - {edition change 2}
----

=== Edition change

Each edition change represents a changes made to the mapping specification in a
specific edition compared to the previous edition.

Syntax:

[source,yaml]
----
version: String (required)
# Version number for this change edition
description: String (optional)
# Description of changes in this edition
mappings:
  - {item change 1}
  - {item change 2}
----

Fields:

`version`:: (required) The version number (integer). Must be positive.
+
[example]
`2`, `3`, `6`.

`description`:: (optional) A multi-line string describing the changes made in
this edition. Should provide a comprehensive overview of what changed and why.
If not provided, a publication may provide its own boilerplate or summary.

`mappings`:: (optional) An array of mapping changes.


=== Mapping change

Each mapping change represents a specific element whose mapping has changed in an
edition.

Syntax:

[source,yaml]
----
name: String (optional)
# Name of the EXPRESS construct whose mapping changed
description: String (optional)
# Description of the mapping change
----

Fields:

`name`:: (optional) The name of the EXPRESS construct whose mapping changed (string).

`description`:: (optional) A description of the mapping change (string).

.Mapping change file from ISO 10303 SRL module product_as_individual_assembly_and_test
[example]
====
[source,yaml]
----
---
schema: product_as_individual_assembly_and_test
editions:
- version: '2'
  mappings:
  - description: Applied_activity_assignment mapping updated
  - description: Applied_process_operation_occurrence mapping updated
  - description: Applied_test_activity mapping updated
- version: '5'
  description: Mapping specifications updated.
----
====

