== Content conversion

=== Schema information conversion

==== General

In a schema if there are lines like this:

[source]
----
ENTITY action_method_with_associated_documents
  SUBTYPE OF (action_method);
  documents : SET [l:?] of document;
END_ENTITY;
----

It means that `action_method_with_associated_documents` is defined in the
current schema.

Given a text like this, we need to convert them:

[source,adoc]
----
An *action_method* defines a potential means of satisfying an *action*.
An *action_method_to_select_from*, an **action_method_with_associated_document**s,
and an *action_method_associated_documents_constrained*,
specify different types of **action_method**s
that may be used to satisfy an action.
----

To reflect the actual EXPRESS entity with schema information:

[source,adoc]
----
An *action_method* defines a potential means of satisfying an *action*.
An <<express:method_definition_schema.action_method_to_select_from,action_method_to_select_from>>,
an <<express:method_definition_schema.action_method_with_associated_document,action_method_with_associated_documents>>,
and an
<<express:method_definition_schema.action_method_associated_documents_constrained,action_method_associated_documents_constrained>>,
specify different types of **action_method**s that may be used to satisfy an action.
----

==== References to external schema

In a schema if there are lines like this:

[source]
----
REFERENCE FROM action_schema
    (action_method,
     action_method_relationship,
     action_relationship);
----

This means that the entities called `action_method`,
`action_method_relationship` and `action_relationship` come from the schema
`action_schema`.

Given a text like this, we need to convert them:

[source,adoc]
----
An *action_method* defines a potential means of satisfying an *action*.
An *action_method_to_select_from*, an **action_method_with_associated_document**s,
and an *action_method_associated_documents_constrained*,
specify different types of **action_method**s
that may be used to satisfy an action.
----

To reflect the actual EXPRESS entity with fully resolved schema information:

[source,adoc]
----
An <<express:action_schema.action_method,action_method>>
defines a potential means of satisfying an
<<express:action_schema.action,action>>.
An *action_method_to_select_from*, an **action_method_with_associated_document**s,
and an *action_method_associated_documents_constrained*, specify different types of
<<express:action_schema.action_method,action_methods>> that may be used to satisfy an action.
----

==== Fully expressed references

Combining the above two approaches, from this text:

[source]
----
An *action_method* defines a potential means of satisfying an *action*.
An *action_method_to_select_from*, an **action_method_with_associated_document**s,
and an *action_method_associated_documents_constrained*,
specify different types of **action_method**s
that may be used to satisfy an action.
----

We get:

[source]
----
An <<express:action_schema.action_method,action_method>>
defines a potential means of satisfying an
<<express:action_schema.action,action>>.
An <<express:method_definition_schema.action_method_to_select_from,action_method_to_select_from>>,
an <<express:method_definition_schema.action_method_with_associated_document,action_method_with_associated_documents>>,
and an
<<express:method_definition_schema.action_method_associated_documents_constrained,action_method_associated_documents_constrained>>,
specify different types of <<express:action_schema.action_method,action_methods>>
that may be used to satisfy an action.
----

=== Example

The converted `method_definition_schema.exp` would look like this:

[source]
----
SCHEMA method_definition_schema;

REFERENCE FROM action_schema
    (action_method,
     action_method_relationship,
     action_relationship);

...

(*"method_definition_schema.__note
The schemas referenced above can be found in the following parts of ISO 10303:

action_schema:: <<iso10303-41>>
document_schema:: <<iso10303-41>>
...
*)

(*"method_definition_schema.__note
See <<annexD>>, <<figD1>>, for a graphical presentation of this schema.
*)

(*"method_definition_schema"
The subject of ...
*)

(*"method_definition_schema.__fund_cons"
The *method_definition_schema* provides...
*)

(*"method_definition_schema.relationship_with_condition"
A *relationship_with_condition* type ...
*)

TYPE relationship_with_condition = SELECT
  (action_method_relationship,
   action_relationship,
   context_dependent_action_method_relationship,
   context_dependent_action_relationship);
END_TYPE;

(*"method_definition_schema.process_or_process_relationship"
A *process_or_process_relationship* type ...
*)

TYPE process_or_process_relationship = SELECT
  (product_definition_process,
   property_process,
   relationship_with_condition);
END_TYPE;

(*"method_definition_schema.action_method_with_associated_documents"
An **action_method_with_associated_document**s is a type ...
*)

(*"method_definition_schema.action_method_with_associated_documents.__example"
A process specification document that ...
*)

ENTITY action_method_with_associated_documents
  SUBTYPE OF (action_method);
  documents : SET [l:?] of document;
END_ENTITY;

...

END_SCHEMA; -- method_definition_schema
----
